### ISSUE TITLE
UnicodeEncodeError in gateway_bootstrap.sendexec() when running Python 3 on Windows

### ISSUE THREAD

**Issue by pshv** [pytest-dev/execnet#88]
I faced with an issue running pytest-xdist module that relies on execnet. Since repr() function works differently on Py2 and Py3:
Py2.7 repr: 
```
>>> 'тест'.__repr__()
"'\\xd1\\x82\\xd0\\xb5\\xd1\\x81\\xd1\\x82'"
```

Py3.7 repr:
```
>>> 'тест'.__repr__()
"'тест'"
```
sendexec() throws a UnicodeEncodeError in the following line:

`io.write((repr(source) + "\n").encode('ascii'))`

That makes it impossible to run pytest-xdist along with execnet package when it's path contains non-ASCII symbols which was the case for me (let's say C:\тест\execnet). As a temporal solution, I made next workaround, but I'm sure there is much better ways to handle that and I didn't tested it well against anything other than my particular case on Windows: https://github.com/pshv/execnet/commit/3e0a6631409fc2d0941f74917b34c092f15083d6

**Comment by pshv** [comment]
Thanks for the quick reply. I'm getting that error on Python 3 only. The easiest sample to reproduce:

1. Install pytest-xdist.
2. Git clone execnet project to some directory with non-ASCII symbols (C:\тест\execnet in my case).
3. Reinstall execnet with the recent git clone version. To be clear:
    - pip uninstall execnet
    - pip install -e C:\тест\execnet
4. Create some small test to run:
```
def test():
    assert True
```
5. Run the test file with -n 1 to enforce xdist plugin
pytest -n 1 test.py

**Comment by nicoddemus** [comment]
Thanks @pshv

**Comment by dsegan** [comment]
FWIW, to me it makes more sense to simply switch the protocol to use UTF-8 instead of ASCII in gateway_bootstrap.py sendexec(). This should help with any code containing unicode strings as well.

I am sure there will be other places (perhaps Popen2IO read method to decode buf) to make it actually work, but changing that line allows me to use pytest "-n" parameter on Ubuntu 18.04 when my code lives in a directory containing Cyrillic in it.

**Comment by RonnyPfannschmidt** [comment]
closing as wontfi, the next release will be python3 only an use unicode-escape
